[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "airbnb_dbt_dagster_project.definitions"
code_location_name = "airbnb_dbt_dagster_project"